name: Release Pipeline
run-name: Release 📦🚀

on:
  workflow_dispatch:
    branches:
      - "main"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Installing Devbox ⚙️
        uses: jetify-com/devbox-install-action@v0.14.0
      - name: Install all dependencies 📦
        run: devbox run install
      - name: Release Version 🏷
        run: echo "RELEASE_VERSION=1.0.$(date +%s)" >> "$GITHUB_ENV"
      - name: Create Tag
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ env.RELEASE_VERSION }}',
              sha: context.sha
            })
      - name: Create Release
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v${{ env.RELEASE_VERSION }}',
              name: 'Release v${{ env.RELEASE_VERSION }}',
              generate_release_notes: true
            })
      - name: 📦 Package
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        run: devbox run build
      - name: 🚀 Publish to PyPI
        run: devbox run publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TWINE_PASSWORD }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
